In [1]:
!pip install opencv-contrib-python


[notice] A new release of pip is available: 25.0 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import cv2

import numpy as np

In [3]:
face_detector = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')

eye_detector = cv2.CascadeClassifier('haarcascade_eye.xml')

In [4]:
img = cv2.imread("D:/DS & AI/CV/1.jpg")

# Check if the image is loaded correctly
if img is None:
    raise ValueError("Image not found or unable to load.")

# Convert to grayscale
gray_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# Load the face detector
face_detector = cv2.CascadeClassifier(cv2.data.haarcascades + "haarcascade_frontalface_default.xml")

# Detect faces
result = face_detector.detectMultiScale(
    gray_img,
    scaleFactor=1.05,
    minNeighbors=5,
    minSize=(30, 30),
    flags=cv2.CASCADE_SCALE_IMAGE
)

# Print the detection results
print(result)

[[1970  315 1802 1802]
 [1674 3610   68   68]
 [ 607 3741   55   55]
 [1288 3855   54   54]
 [4651 3918   58   58]
 [4867 3167   56   56]
 [2144 3221   60   60]
 [4756 2802  100  100]
 [1150 2817  122  122]
 [1693 3234  393  393]
 [4855 3188   53   53]
 [ 751 3124   84   84]
 [4296 3040   87   87]
 [ 952 3232   92   92]
 [2669 3340   35   35]
 [2079 2874  115  115]
 [4899 3272  104  104]
 [1226 3276  105  105]
 [1252 3223   34   34]
 [ 777 3296   46   46]
 [4798 3341   55   55]
 [ 706 3518   63   63]
 [2275 2674   89   89]
 [4446 3421   72   72]
 [1145 3482   85   85]
 [4928 3177  108  108]]


In [11]:
faces = face_detector.detectMultiScale(gray_img, 1.3,5)

for (x,y,w,h) in faces:
    cv2.rectangle(img, (x,y),(x+w,y+h), (0,255,0),2)

cv2.imshow('img',img)
cv2.waitKey(0)

-1